// Code generated by "stringer -type=BackendType"; DO NOT EDIT.

package storage

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Basic-0]
	_ = x[Race-1]
	_ = x[Sharded-2]
	_ = x[Sync-3]
	_ = x[FileBacked-4]
	_ = x[CachedFileBacked-5]
}

const _BackendType_name = "BasicRaceShardedSyncFileBackedCachedFileBacked"

var _BackendType_index = [...]uint8{0, 5, 9, 16, 20, 30, 46}

func (i BackendType) String() string {
	if i < 0 || i >= BackendType(len(_BackendType_index)-1) {
		return "BackendType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BackendType_name[_BackendType_index[i]:_BackendType_index[i+1]]
}
